eureka:
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${eureka.instance.ip-address}:${server.port} # 状态显示格式

server:
  port: 9999
